# Generated by Django 4.2.7 on 2025-07-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_from_party_transaction_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Account balance after transaction', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='branch_code',
            field=models.CharField(blank=True, help_text='Branch Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Cheque/Reference Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text='Description from bank statement', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payee_recipient_name',
            field=models.CharField(blank=True, help_text='Payee/Recipient Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purpose',
            field=models.TextField(blank=True, help_text='Purpose of transaction', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value_date',
            field=models.DateField(blank=True, help_text='Value Date from bank statement', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
