# Generated by Django 4.2.7 on 2025-07-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_balance_transaction_branch_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payee_recipient_name',
            field=models.CharField(blank=True, choices=[('Staff', 'Staff'), ('Employees', 'Employees'), ('Contractors', 'Contractors'), ('Suppliers', 'Suppliers'), ('Vendors', 'Vendors'), ('Government', 'Government'), ('Corporate', 'Corporate'), ('Individuals', 'Individuals'), ('Banks', 'Banks'), ('Insurance Companies', 'Insurance Companies'), ('Utility Companies', 'Utility Companies'), ('Transport Services', 'Transport Services'), ('Training Institutes', 'Training Institutes'), ('Audit Firms', 'Audit Firms'), ('Legal Firms', 'Legal Firms'), ('Marketing Agencies', 'Marketing Agencies'), ('Hotels', 'Hotels'), ('Restaurants', 'Restaurants'), ('Equipment Suppliers', 'Equipment Suppliers'), ('Stationary Suppliers', 'Stationary Suppliers'), ('Members', 'Members'), ('Donors', 'Donors'), ('Investors', 'Investors'), ('Others', 'Others')], help_text='Payee/Recipient Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Salary Payment', 'Salary Payment'), ('Office Rent', 'Office Rent'), ('Equipment Purchase', 'Equipment Purchase'), ('Transport Expenses', 'Transport Expenses'), ('Stationary Purchase', 'Stationary Purchase'), ('Training Expenses', 'Training Expenses'), ('Maintenance', 'Maintenance'), ('Utility Bills', 'Utility Bills'), ('Insurance', 'Insurance'), ('Legal Fees', 'Legal Fees'), ('Audit Fees', 'Audit Fees'), ('Marketing Expenses', 'Marketing Expenses'), ('Travel Expenses', 'Travel Expenses'), ('Food & Refreshments', 'Food & Refreshments'), ('Grant Received', 'Grant Received'), ('Donation Received', 'Donation Received'), ('Membership Fees', 'Membership Fees'), ('Loan Repayment', 'Loan Repayment'), ('Investment Income', 'Investment Income'), ('Other Income', 'Other Income'), ('Other Expenses', 'Other Expenses')], help_text='Purpose of transaction', max_length=100, null=True),
        ),
    ]
