# Generated by Django 4.2.7 on 2025-07-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_payee_recipient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payee_recipient_name',
            field=models.CharField(blank=True, help_text='Payee/Recipient Name (actual person name)', max_length=200, null=True),
        ),
    ]
